name: Android CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
          cache: gradle

      - name: Grant execute permission for gradlew
        working-directory: ./apps/mobileattester
        run: chmod +x gradlew
      - name: Build with Gradle
        working-directory: ./apps/mobileattester
        run: ./gradlew build

lint:
  needs: [build]
  runs-on: ubuntu-latest
  steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Run lint
      working-directory: ./apps/mobileattester
      run: ./gradlew lintDebug
    - name: Upload html test report
      working-directory: ./apps/mobileattester
      uses: actions/upload-artifact@v2
      with:
        name: lint.html
        path: ./app/build/reports/lint-results-debug.html

test:
  needs: [lint]
  name: Run Unit Tests
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: "11"
        distribution: "adopt"
        cache: gradle
    - name: Run unit tests
      working-directory: ./apps/mobileattester
      run: bash ./gradlew test --stacktrace
    - name: Upload test report
      working-directory: ./apps/mobileattester
      uses: actions/upload-artifact@v2
      with:
        name: unit_test_report
        path: ./app/build/reports/tests/testDebugUnitTest/

apk:
  needs: [test]
  name: Generate APK
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build APK
      working-directory: ./apps/mobileattester
      run: ./gradlew assembleDebug
    - name: Upload APK
      working-directory: ./apps/mobileattester
      uses: actions/upload-artifact@v2
      with:
        name: expense-manager.apk
        path: ./app/build/outputs/apk/debug/app-debug.apk
