name: Android CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
          cache: gradle

      - name: Grant execute permission for gradlew
        working-directory: ./apps/mobileattester
        run: chmod +x gradlew
      - name: Build with Gradle
        working-directory: ./apps/mobileattester
        run: ./gradlew build

  test:
    needs: [build]
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
          cache: gradle
      - name: Run unit tests
        working-directory: ./apps/mobileattester
        run: bash ./gradlew test --stacktrace

  apk:
    needs: [test]
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build APK
        working-directory: ./apps/mobileattester
        run: ./gradlew assembleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: expense-manager.apk
          path: ./app/build/outputs/apk/debug/app-debug.apk
